import { getSupabaseAdmin, getAuthBase, getApiBase } from "../_shared/ebay-client.ts";
Deno.serve(async (req: Request) => {
  const url = new URL(req.url);
  const code = url.searchParams.get("code");
  const stateParam = url.searchParams.get("state");
  if (!code || !stateParam) return new Response("Missing code or state", { status: 400 });
  const { userId, accountLabel } = JSON.parse(atob(stateParam));
  const appId = Deno.env.get("EBAY_APP_ID")!;
  const certId = Deno.env.get("EBAY_CERT_ID")!;
  const redirectUri = Deno.env.get("EBAY_REDIRECT_URI")!;
  const authBase = getAuthBase("PRODUCTION");
  const apiBase = getApiBase("PRODUCTION");
  const credentials = btoa(`${appId}:${certId}`);
  const tokenResponse = await fetch(`${authBase}/oauth2/token`, { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", Authorization: `Basic ${credentials}` }, body: new URLSearchParams({ grant_type: "authorization_code", code, redirect_uri: redirectUri }) });
  if (!tokenResponse.ok) return new Response(`Token exchange failed: ${await tokenResponse.text()}`, { status: 500 });
  const tokenData = await tokenResponse.json();
  const userResponse = await fetch(`${apiBase}/commerce/identity/v1/user/`, { headers: { Authorization: `Bearer ${tokenData.access_token}`, "Content-Type": "application/json" } });
  const userData = await userResponse.json();
  const ebayUserId = userData.username || userData.userId || "unknown";
  const supabase = getSupabaseAdmin();
  const expiresAt = new Date(Date.now() + tokenData.expires_in * 1000).toISOString();
  const { error } = await supabase.from("ebay_accounts").upsert({ user_id: userId, ebay_user_id: ebayUserId, account_label: accountLabel, access_token: tokenData.access_token, refresh_token: tokenData.refresh_token, token_expires_at: expiresAt, token_scope: tokenData.scope, ebay_app_id: appId, ebay_cert_id: certId, ebay_dev_id: Deno.env.get("EBAY_DEV_ID"), sync_status: "never" }, { onConflict: "user_id,ebay_user_id" });
  if (error) return new Response(`Database error: ${error.message}`, { status: 500 });
  const appUrl = Deno.env.get("APP_URL") || "http://localhost:5173";
  return Response.redirect(`${appUrl}/settings?connected=true`, 302);
});
